let users = [
  {
    id: "1",
    username: "Sourav Kumar Dash",
    email: "me.souravdash@gmail.com",
    password: "2002",
    accountType: "premium",
    accountBalance: 5000,
    state: "Odisha",
    number: "6371396500",
    age: 22,
    photo: "path_to_photo1",
  },
  {
    id: "2",
    username: "jane_smith",
    email: "jane@example.com",
    password: "password123",
    accountType: "standard",
    accountBalance: 3000,
    state: "New York",
    number: "0987654321",
    age: 20,
    photo: "path_to_photo2",
  },
  {
    id: "3",
    username: "alice_jones",
    email: "alice@example.com",
    password: "password123",
    accountType: "premium",
    accountBalance: 7000,
    state: "Texas",
    number: "1231231234",
    age: 20,
    photo: "path_to_photo3",
  },
  {
    id: "4",
    username: "bob_brown",
    email: "bob@example.com",
    password: "password123",
    accountType: "standard",
    accountBalance: 2000,
    state: "Florida",
    number: "4564564567",
    age: 20,
    photo: "path_to_photo4",
  },
  {
    id: "5",
    username: "charlie_davis",
    email: "charlie@example.com",
    password: "password123",
    accountType: "premium",
    accountBalance: 8000,
    state: "Nevada",
    number: "7897897890",
    age: 20,
    photo: "path_to_photo5",
  },
  {
    id: "6",
    username: "david_wilson",
    email: "david@example.com",
    password: "password123",
    accountType: "standard",
    accountBalance: 1500,
    state: "Ohio",
    number: "1472583690",
    age: 20,
    photo: "path_to_photo6",
  },
  {
    id: "7",
    username: "ella_moore",
    email: "ella@example.com",
    password: "password123",
    accountType: "premium",
    accountBalance: 4500,
    state: "Illinois",
    number: "9638527410",
    age: 20,
    photo: "path_to_photo7",
  },
  {
    id: "8",
    username: "frank_thomas",
    email: "frank@example.com",
    password: "password123",
    accountType: "standard",
    accountBalance: 2800,
    state: "Georgia",
    number: "7412589630",
    age: 20,
    photo: "path_to_photo8",
  },
  {
    id: "9",
    username: "grace_clark",
    email: "grace@example.com",
    password: "password123",
    accountType: "premium",
    accountBalance: 6000,
    state: "Michigan",
    number: "8529637410",
    age: 20,
    photo: "path_to_photo9",
  },
  {
    id: "10",
    username: "harry_lewis",
    email: "harry@example.com",
    password: "password123",
    accountType: "standard",
    accountBalance: 3200,
    state: "Virginia",
    number: "3692581470",
    age: 20,
    photo: "path_to_photo10",
  },
  {
    id: "11",
    username: "irene_walker",
    email: "irene@example.com",
    password: "password123",
    accountType: "premium",
    accountBalance: 5500,
    state: "Washington",
    number: "1473692580",
    age: 20,
    photo: "path_to_photo11",
  },
  {
    id: "12",
    username: "jack_hall",
    email: "jack@example.com",
    password: "password123",
    accountType: "standard",
    accountBalance: 4000,
    state: "Arizona",
    number: "2587413690",
    age: 20,
    photo: "path_to_photo12",
  },
  {
    id: "13",
    username: "karen_king",
    email: "karen@example.com",
    password: "password123",
    accountType: "premium",
    accountBalance: 7300,
    state: "Oregon",
    number: "3697412580",
    age: 20,
    photo: "path_to_photo13",
  },
  {
    id: "14",
    username: "larry_lee",
    email: "larry@example.com",
    password: "password123",
    accountType: "standard",
    accountBalance: 2700,
    state: "Colorado",
    number: "8521479630",
    age: 20,
    photo: "path_to_photo14",
  },
  {
    id: "15",
    username: "maria_harris",
    email: "maria@example.com",
    password: "password123",
    accountType: "premium",
    accountBalance: 6100,
    state: "Minnesota",
    number: "7413698520",
    age: 20,
    photo: "path_to_photo15",
  },
  {
    id: "16",
    username: "nancy_martin",
    email: "nancy@example.com",
    password: "password123",
    accountType: "standard",
    accountBalance: 3500,
    state: "Massachusetts",
    number: "9631478520",
    age: 20,
    photo: "path_to_photo16",
  },
  {
    id: "17",
    username: "oscar_garcia",
    email: "oscar@example.com",
    password: "password123",
    accountType: "premium",
    accountBalance: 4900,
    state: "Missouri",
    number: "2589637410",
    age: 20,
    photo: "path_to_photo17",
  },
  {
    id: "18",
    username: "peter_robinson",
    email: "peter@example.com",
    password: "password123",
    accountType: "standard",
    accountBalance: 2200,
    state: "Indiana",
    number: "1478523690",
    age: 20,
    photo: "path_to_photo18",
  },
  {
    id: "19",
    username: "quincy_white",
    email: "quincy@example.com",
    password: "password123",
    accountType: "premium",
    accountBalance: 6500,
    state: "Kentucky",
    number: "3692587410",
    age: 20,
    photo: "path_to_photo19",
  },
  {
    id: "20",
    username: "rachel_clark",
    email: "rachel@example.com",
    password: "password123",
    accountType: "standard",
    accountBalance: 3100,
    state: "Louisiana",
    number: "7419632580",
    age: 20,
    photo: "path_to_photo20",
  },
  {
    id: "21",
    username: "samuel_lopez",
    email: "samuel@example.com",
    password: "password123",
    accountType: "premium",
    accountBalance: 7200,
    state: "Oklahoma",
    number: "8523691470",
    age: 20,
    photo: "path_to_photo21",
  },
  {
    id: "22",
    username: "tina_wilson",
    email: "tina@example.com",
    password: "password123",
    accountType: "standard",
    accountBalance: 2300,
    state: "Connecticut",
    number: "2581479630",
    age: 20,
    photo: "path_to_photo22",
  },
  {
    id: "23",
    username: "ursula_smith",
    email: "ursula@example.com",
    password: "password123",
    accountType: "premium",
    accountBalance: 5700,
    state: "Iowa",
    number: "9632587410",
    age: 20,
    photo: "path_to_photo23",
  },
  {
    id: "24",
    username: "victor_evans",
    email: "victor@example.com",
    password: "password123",
    accountType: "standard",
    accountBalance: 2400,
    state: "Arkansas",
    number: "1473698520",
    age: 20,
    photo: "path_to_photo24",
  },
  {
    id: "25",
    username: "wendy_taylor",
    email: "wendy@example.com",
    password: "password123",
    accountType: "premium",
    accountBalance: 6400,
    state: "West Virginia",
    number: "3697418520",
    age: 20,
    photo: "path_to_photo25",
  },
  {
    id: "26",
    username: "xander_allen",
    email: "xander@example.com",
    password: "password123",
    accountType: "standard",
    accountBalance: 2700,
    state: "Nebraska",
    number: "8529637410",
    age: 20,
    photo: "path_to_photo26",
  },
  {
    id: "27",
    username: "yolanda_hill",
    email: "yolanda@example.com",
    password: "password123",
    accountType: "premium",
    accountBalance: 5900,
    state: "Utah",
    number: "1478529630",
    age: 20,
    photo: "path_to_photo27",
  },
];

export let addUser = (newUser) => {
  users = [...users, { ...newUser, id: users.length + 1 }];
};

addUser()

export default users;
